### ISSUE TITLE
Support for STI

### ISSUE THREAD

**Issue by youssef1337** [ankane/disco#25]
Hey @ankane, would you be open for supporting STI? because I can't find a way to get `recommended_items` if I have a model inheriting from another model, example `AdminUser` inheriting from `User` in this case the `subject_type` will be `AdminUser` but it will query `User` when using the `recommended_items` function. Below you can find the change I made to make it work for this use case, I can open a PR if you're open to this change.

![image](https://user-images.githubusercontent.com/22629501/211757251-8a8692fd-7c9b-43e7-a60a-540a9657d5a4.png)

Then I used it like this
```ruby
has_recommended :items, subject_type: 'User'
```

**Comment by ankane** [comment]
Hey @youssef1337, thanks for reporting! Looks like this was a bug. Fixed in the commit above.

**Comment by youssef1337** [comment]
@ankane I just tested that commit and I took a look at it and I don't understand how is that going to make any difference? the `subject_type` was being passed [here](https://github.com/ankane/disco/blob/033052a1a38dadb7f8735b9a4c40bdf505964b92/lib/disco/model.rb#L16) as `model_name.name` then it got moved to a variable in that commit - that doesn't change the behvaior at all, I still get my recommendations saved with the `AdminUser` as the `subject_type` and queried with `User` as the `subject_type`.

**Comment by ankane** [comment]
Try printing `model_name.name` in each of those places to see how they're different.
